version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_HOST: "%"                       # ✅ cho phép root connect từ mọi IP
    command: --default-authentication-plugin=mysql_native_password   # ✅ dùng auth kiểu cũ, dễ connect
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: ecommerce-app
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Nếu muốn override DB/Redis bằng env thay vì application-docker.yaml thì mở comment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: root
      # SPRING_DATA_REDIS_HOST: redis
      # SPRING_DATA_REDIS_PORT: 6379

volumes:
  mysql_data:
